# Generated by Django 6.0.6 on 2026-06-27 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('quality', 'Data Quality'), ('anomaly', 'Anomaly'), ('security', 'Security')], default='quality', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('upload', 'Dataset Uploaded'), ('view', 'Dataset Viewed'), ('delete', 'Dataset Deleted'), ('login', 'User Logged In'), ('login_failed', 'Login Failed'), ('logout', 'User Logged Out'), ('register', 'User Registered'), ('export', 'Report Exported'), ('password_change', 'Password Changed'), ('password_reset_request', 'Password Reset Requested'), ('profile_update', 'Profile Updated'), ('access_denied', 'Access Denied'), ('analytics_view', 'Analytics Viewed'), ('quality_view', 'Quality Report Viewed'), ('anomaly_view', 'Anomaly Report Viewed'), ('retention_expired', 'Dataset Retention Expired')], max_length=40),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
